### ISSUE TITLE
I/O Error exception when calling Bootstrap.BindAsync()

### ISSUE THREAD

**Issue by romanovmv** [Azure/DotNetty#185]
I'm just trying to run QuoteOfTheMoment.Client example and get this exception. Any ideas?

**Comment by nayato** [comment]
@romanovmv what is the exception though?

**Comment by romanovmv** [comment]
@nayato I/O Error
`Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> DotNetty.Transport.Channels.ClosedChannelException: I/O error occurred.
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<DoBindAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dotnetty.Program.<RunClientAsync>d__0.MoveNext() in C:\Temp\Dotnetty\Dotnetty\Program.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotnetty.Program.<RunClientAsync>d__0.MoveNext() in C:\Temp\Dotnetty\Dotnetty\Program.cs:line 55
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Dotnetty.Program.Main() in C:\Temp\Dotnetty\Dotnetty\Program.cs:line 58`

**Comment by nayato** [comment]
I've just fixed a couple of issues in QOTM sample, trying to cast to `ISocketChannel` namely. Let me know if this fixes your issue.

**Comment by romanovmv** [comment]
@nayato thank you, now it's working fine!
