### ISSUE TITLE
Exception when receive message on Linux

### ISSUE THREAD

**Issue by ZhaoXiangXML** [Azure/DotNetty#204]
I'm trying to deploy my project based on dotnet core 1.1.1 and DotNetty 0.4.2 to a CentOS 7 machine. Which worked fine when debugging on Windows.

There is an warning every time I connect:

```
info: DotNetty.Handlers.Logging.LoggingHandler[0]
      [id: 0x2c5ab5dc, [::ffff:192.168.29.131]:3724] RECEIVED: [id: 0x697be0b0, [::ffff:192.168.29.1]:51555 => [::ffff:192.168.29.131]:3724]
warn: DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel[0]
      Failed to create a new channel from an accepted socket.
System.ArgumentException: The socket handle is not valid.
   at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
   at System.Net.Sockets.Socket.Accept()
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
info: DotNetty.Handlers.Logging.LoggingHandler[0]
      [id: 0x2c5ab5dc, [::ffff:192.168.29.131]:3724] EXCEPTION: System.ArgumentException: The socket handle is not valid.
         at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
         at System.Net.Sockets.Socket.Accept()
         at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
System.ArgumentException: The socket handle is not valid.
   at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
   at System.Net.Sockets.Socket.Accept()
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
warn: DotNetty.Transport.Channels.DefaultChannelPipeline[0]
      An ExceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
System.ArgumentException: The socket handle is not valid.
   at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
   at System.Net.Sockets.Socket.Accept()
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)

```

However things seems to be working, I can see my Console output when I send message from client.

Is this something I should concern about?

**Comment by StormHub** [comment]
Hey, would you be able to test it on either IPv4 and IPv6 separately how this behaves? I am very curious about this. The stacktrace looks like dual stack is enabled.

**Comment by ZhaoXiangXML** [comment]
@StormHub , indeed both stacks were enabled, however I was connecting with a IPv4 address. I tried to disable IPv6 and I got the following stacktrace:

```
info: DotNetty.Handlers.Logging.LoggingHandler[0]
      [id: 0x32508a2b, [::ffff:192.168.29.131]:3724] RECEIVED: [id: 0x395cda49, [::ffff:192.168.29.1]:53305 => [::ffff:192.168.29.131]:3724]
warn: DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel[0]
      Failed to create a new channel from an accepted socket.
System.ArgumentException: The socket handle is not valid.
   at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
   at System.Net.Sockets.Socket.Accept()
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
info: DotNetty.Handlers.Logging.LoggingHandler[0]
      [id: 0x32508a2b, [::ffff:192.168.29.131]:3724] EXCEPTION: System.ArgumentException: The socket handle is not valid.
         at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
         at System.Net.Sockets.Socket.Accept()
         at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
System.ArgumentException: The socket handle is not valid.
   at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
   at System.Net.Sockets.Socket.Accept()
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
warn: DotNetty.Transport.Channels.DefaultChannelPipeline[0]
      An ExceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
System.ArgumentException: The socket handle is not valid.
   at System.Net.Sockets.Socket..ctor(SafeCloseSocket fd)
   at System.Net.Sockets.Socket.Accept()
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocketChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)

```

I don't think it makes any difference.

Unfortunately I don't know how to disable IPv6.

**Comment by StormHub** [comment]
I have seen something similar while debugging on Linux, running on IPv4 only or IPv6 only solves the issues. It might be something related to Net Core. What is the .Net Core version this is running on?

**Comment by ZhaoXiangXML** [comment]
I'm using .Net Core 1.1.1 on a CentOS 7 virtual machine. I'm connecting from an Unity game from Windows host. The VM network is set to NAT.

**Comment by nayato** [comment]
socket handle is not valid usually indicates that socket got closed before any operation could be carried out on it but we're still trying to do something with it. Can you please try 0.4.3 to see if you would get more logging / issues?

**Comment by ZhaoXiangXML** [comment]
Hi @nayato, I tried v0.4.3 and got the same error. I don't think there's any more logging

Please note my client connection works just fine.
