### ISSUE TITLE
Converting IByteBuffer to byte[] throws IndexOutOfRangeException with UnpooledByteBufferAllocator

### ISSUE THREAD

**Issue by varunpuranik** [Azure/DotNetty#415]
We use the following code to convert an IByteBuffer to a byte[] - 
```
        public byte[] ToByteArray(IByteBuffer byteBuffer)
        {
            if (!byteBuffer.IsReadable())
            {
                return new byte[0];
            }
            using (var stream = new ReadOnlyByteBufferStream(byteBuffer, false))
            {
                var memoryStream = new MemoryStream();
                stream.CopyTo(memoryStream);
                byte[] bytes = memoryStream.ToArray();
                return bytes;
            }
        }
```

But this throws an IndexOutOfRangeException with the following callstack - 

at DotNetty.Buffers.UnpooledUnsafeDirectByteBuffer.Addr(Int32 index) in E:\workspace\DotNetty\src\DotNetty.Buffers\UnpooledUnsafeDirectByteBuffer.cs:line 339
   at DotNetty.Buffers.UnpooledUnsafeDirectByteBuffer.GetBytes(Int32 index, Byte[] dst, Int32 dstIndex, Int32 length) in E:\workspace\DotNetty\src\DotNetty.Buffers\UnpooledUnsafeDirectByteBuffer.cs:line 211
   at DotNetty.Buffers.AbstractByteBuffer.ReadBytes(Byte[] destination, Int32 dstIndex, Int32 length) in E:\workspace\DotNetty\src\DotNetty.Buffers\AbstractByteBuffer.cs:line 998
   at DotNetty.Buffers.ReadOnlyByteBufferStream.Read(Byte[] output, Int32 offset, Int32 count) in E:\workspace\DotNetty\src\DotNetty.Buffers\ReadOnlyByteBufferStream.cs:line 46
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at DotnettyTest1.ByteBufferConverter.ToByteArray(IByteBuffer byteBuffer) in C:\Users\vpuranik.REDMOND\Documents\Visual Studio 2017\Projects\DotnettyTest1\DotnettyTest1\ByteBufferConverter.cs:line 34
   at DotnettyTest1.Program.ByteBufferTest1() in C:\Users\vpuranik.REDMOND\Documents\Visual Studio 2017\Projects\DotnettyTest1\DotnettyTest1\Program.cs:line 26
   at DotnettyTest1.Program.Main(String[] args) in C:\Users\vpuranik.REDMOND\Documents\Visual Studio 2017\Projects\DotnettyTest1\DotnettyTest1\Program.cs:line 11

**Comment by yyjdelete** [comment]
https://github.com/Azure/DotNetty/blob/5249d8de2aa9554f49bb3044d0ca2ed03d92f377/test/DotNetty.Buffers.Tests/ReadOnlyByteBufferStreamTests.cs#L143-L152
Not sure why is not catch by `ReadOnlyByteBufferStreamTests.ReadZeroBytesFromTheEndOfTheStream`, but maybe an `if (read == 0) return 0;` should be added here after `Math.Min`, or it may be an bug of `UnpooledUnsafeDirectByteBuffer` if `IByteBuffer` allow to read 0 bytes at the end?
https://github.com/Azure/DotNetty/blob/6b86b1b88398ad658a3b12d0ffdbca4f10a0ab2d/src/DotNetty.Buffers/ReadOnlyByteBufferStream.cs#L38-L48

**Comment by varunpuranik** [comment]
Yes, that is the code I used as well. But it feels like the code above should work as well.

**Comment by erwan-joly** [comment]
```((Span<byte>) directBuf.Array).Slice(directBuf.ArrayOffset, directBuf.ReadableBytes)```
this is the way i'm using to avoid allocation
