### ISSUE TITLE
AggregateException on WSL Ubuntu for missing paths (e.g. /proc/sys/net/ipv4/conf/eth0/forwarding)

### ISSUE THREAD

**Issue by drwill-ms** [Azure/DotNetty#527]
When using DotNetty v0.6 on WSL Ubuntu, an exception is thrown and the call fails.

## Environment

- Using with the Azure IoT .NET SDKs (DeviceClient and DPS client)
- Ubuntu (16.04 and 18.04) in WSL on Windows 10
- .NET Core 2.1 portable app
- The paths listed in the exception are not present. Under **/proc/sys/net/ipv4** the only other directory is **ip_forward**, which is empty.

## Exception details

```
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.TypeInitializationException: The type initializer for 'DotNetty.Transport.Channels.DefaultChannelId' threw an exception. ---> System.Net.NetworkInformation.NetworkInformationException: An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth3/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth4/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth3/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth3/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth4/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth4/forwarding'.) ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at DotNetty.Common.Internal.MacAddressUtil.GetBestAvailableMac()
   at DotNetty.Transport.Channels.DefaultChannelId.DefaultMachineId()
   at DotNetty.Transport.Channels.DefaultChannelId..cctor()
   --- End of inner exception stack trace ---
   at DotNetty.Transport.Channels.AbstractChannel.NewId()
   at DotNetty.Transport.Channels.AbstractChannel..ctor(IChannel parent)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.ClientWebSocketChannel..ctor(IChannel parent, ClientWebSocket webSocket) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\ClientWebSocketChannel.cs:line 29
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass85_0.<<CreateWebSocketChannelFactory>b__0>d.MoveNext() in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 999
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 566
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 176
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\ProtocolRoutingDelegatingHandler.cs:line 112
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 169
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 191
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext() in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 524
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 461
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext() in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken) in C:\code\drwill-ms\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 77
   at TlsProtocolTests.DeviceClientTests.RunTest(String deviceCs) in C:\code\drwill-ms\azure-iot-sdk-csharp\tools\TLS Protocols Tests\DeviceClientTests.cs:line 34
Sending: { "deviceClientTestNumber": 7, "transportType": "Mqtt_Tcp_Only" }
Failed for Mqtt_Tcp_Only due to:
 - Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 - System.TypeInitializationException: The type initializer for 'DotNetty.Transport.Channels.DefaultChannelId' threw an exception.
 - System.Net.NetworkInformation.NetworkInformationException: An error was encountered while querying information from the operating system.
 - System.AggregateException: One or more errors occurred. (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth3/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth4/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth3/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth3/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi1/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/wifi2/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth4/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth4/forwarding'.)
 - System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.
```

**Comment by drwill-ms** [comment]
Per offline request, tested with Ubuntu VM in Azure, and the error is NOT seen there. This only occurs on Ubuntu on Windows Subsystem for Linux.
